package main

import (
	"crypto/rand"
	"fmt"
	"os"
	"sort"
	"strings"
)

// encrypt obfuscates a plaintext string using the same position-dependent XOR
// key schedule as obfuscate.Decrypt. Each encryption uses a random salt so the
// same plaintext yields different ciphertexts.
func encrypt(plain string) []byte {
	var salt [1]byte
	if _, err := rand.Read(salt[:]); err != nil {
		panic(err)
	}
	// Ensure salt is non-zero so the round count is deterministic and > 0.
	if salt[0] == 0 {
		salt[0] = 0xB7
	}
	n := len(plain)
	out := make([]byte, n+1)
	out[0] = salt[0]
	copy(out[1:], plain)

	rounds := 5 + int(salt[0])%5
	for i := 0; i < n; i++ {
		out[i+1] ^= obfKey(salt[0], i, rounds)
	}
	return out
}

func obfKey(salt byte, pos, rounds int) byte {
	k := salt
	for r := 0; r < rounds; r++ {
		k = (k*9 + 17) ^ byte(pos) ^ byte(r)
	}
	return k
}

func byteArrayLiteral(b []byte) string {
	var sb strings.Builder
	for _, v := range b {
		sb.WriteString(fmt.Sprintf("0x%02X, ", v))
	}
	return sb.String()
}

func main() {
	path := "internal/obfuscate/strings.txt"
	data, err := os.ReadFile(path)
	if err != nil {
		fmt.Fprintf(os.Stderr, "cannot read %s: %v\n", path, err)
		os.Exit(1)
	}

	lines := strings.Split(strings.TrimSpace(string(data)), "\n")
	entries := make(map[string]string)
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		idx := strings.Index(line, "=")
		if idx < 0 {
			continue
		}
		name := strings.TrimSpace(line[:idx])
		value := strings.TrimSpace(line[idx+1:])
		// Allow escape sequences like \n, \t, \x00
		value = unescape(value)
		entries[name] = value
	}

	var names []string
	for name := range entries {
		names = append(names, name)
	}
	sort.Strings(names)

	var sb strings.Builder
	sb.WriteString("// Code generated by cmd/genobf. DO NOT EDIT.\n\n")
	sb.WriteString("package obfuscate\n\n")
	for _, name := range names {
		value := entries[name]
		obf := encrypt(value)
		sb.WriteString(fmt.Sprintf("// %s = %q\n", name, value))
		sb.WriteString(fmt.Sprintf("func %s() string {\n\treturn Decrypt([]byte{%s})\n}\n\n", name, byteArrayLiteral(obf)))
	}

	outPath := "internal/obfuscate/z_obfuscated.go"
	if err := os.WriteFile(outPath, []byte(sb.String()), 0644); err != nil {
		fmt.Fprintf(os.Stderr, "cannot write %s: %v\n", outPath, err)
		os.Exit(1)
	}
	fmt.Printf("Generated %s with %d strings\n", outPath, len(names))
}

func unescape(s string) string {
	var out strings.Builder
	for i := 0; i < len(s); i++ {
		if s[i] == '\\' && i+1 < len(s) {
			switch s[i+1] {
			case 'n':
				out.WriteByte('\n')
				i++
			case 't':
				out.WriteByte('\t')
				i++
			case 'r':
				out.WriteByte('\r')
				i++
			case '\\':
				out.WriteByte('\\')
				i++
			default:
				out.WriteByte(s[i])
			}
		} else {
			out.WriteByte(s[i])
		}
	}
	return out.String()
}
